### ISSUE TITLE
help wanted: what is the purpose of optional block?

### ISSUE THREAD

**Issue by zytegalaxy** [m1geo/Pi5_PCIe#3]
I was wondering what is the purpose of this optional block (oscillator):

<img width="761" alt="Screenshot 2023-11-19 at 11 07 23 PM" src="https://github.com/m1geo/Pi5_PCIe/assets/94014876/704f52cd-421a-4b1c-ab65-a9eb2dd58c93">

I guess it would be possible to get full power via FPC connector and connection to Raspberry Pi header 5v is optional?

**Comment by mfolejewski** [comment]
that's SUSCLK (32kHz)

"SUSCLK is a 32 kHz clock useful for card power-saving but not required in practice"

https://hackaday.com/2022/11/03/m-2-for-hackers-connectors/

**Comment by m1geo** [comment]
Correct. It is to allow peripheral devices to operate from a slow, low power clock in order to do things like assert PCIE_WAKE#. Useful for things like wake-on-LAN.

The FPC connector is able to supply 1A (500mA per pin) at 5V. This is enough for some PCIe/NVMe devices, but not all. If you need more current, the additional power from the GPIO pins may be helpful. They appear to be connected together based on a simple DC resistance check.
